name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your default branch
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the version specified in your project, if applicable

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build # Ensure your `package.json` includes the `build` script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # Replace with the output directory of your Astro build
