name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your default branch name

permissions:
  contents: write # Ensure write permissions for deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version you want to use
          cache: "npm" # Cache node_modules to speed up builds

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the Astro project
      - name: Build the project
        run: npm run gh-pages:build # Ensure this matches your build script in package.json

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub-provided token
          publish_dir: dist # Directory with the built site
          keep_files: true
